### ISSUE TITLE
Compatibility with WebStorm

### ISSUE THREAD

**Issue by segrey** [mysticatea/eslint-cli#2]
Hi!

Currently, it's impossible to specify path to eslint-cli package in WebStorm as ESLint package (Settings | Languages & Frameworks | JavaScript | Code Quality Tools | ESLint).
The problem is that WebStorm uses `<package-dir>/bin/eslint.js` when running eslint for a file. However, there is no `eslint-cli/bin/eslint.js` (instead there is `eslint-cli/bin/eslint-cli.js`).

Could you please rename `bin/eslint-cli.js` to `bin/eslint.js` to make eslint-cli and eslint compatible?

**Comment by mysticatea** [comment]
Thank you for this issue.

Curiosity, why don't you use the local eslint directly?
I'm not an WebStorm familiar, though, we can configure eslint for each project on the tool.

**Comment by q42jaap** [comment]
@mysticatea I have multiple .eslintrc's in 1 project. The files have different plugins listed in them, and the package.json is also different. Webstorm finds the .eslintrc file nearest to the file that's checked, and executes the eslint command from that directory.
Configuring the local eslint from node_modules makes you choose between the folders. Because of the plugins that may be different, you can get errors.

I hope that made sense...

**Comment by mysticatea** [comment]
@q42jaap Interesting. Thank you for the explanation.

OK, I will rename it.
This seems convenience for monorepo projects.

**Comment by mysticatea** [comment]
I released v1.1.0.

https://github.com/mysticatea/eslint-cli/releases/tag/v1.1.0

**Comment by q42jaap** [comment]
Thank you!
FYI:
```
/usr/local/bin/eslint -> /usr/local/lib/node_modules/eslint-cli/bin/eslint.js
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/5.5.0/bin/node" "/usr/local/bin/npm" "install" "-g" "eslint-cli"
npm ERR! node v5.5.0
npm ERR! npm  v3.5.3
npm ERR! path /usr/local/bin/eslint-cli
npm ERR! code EEXIST

npm ERR! Refusing to delete /usr/local/bin/eslint-cli: ../lib/node_modules/eslint-cli/bin/eslint-cli.js symlink target is not controlled by npm /usr/local
npm ERR! File exists: /usr/local/bin/eslint-cli
npm ERR! Move it away, and try again.
```

I don't know whether you can do anything about it, but maybe you'd want that in a release note, or in the readme? I just deleted the two symlinks.

**Comment by mysticatea** [comment]
Oh no!

... On Windows it was no problem.

**Comment by mysticatea** [comment]
I updated the release note of this.

**Comment by segrey** [comment]
@mysticatea Great! Thank you very much!
